version: '3.7'

services:

  builder:
    build: ./builder
    volumes: 
      - app_volume:/opt/build

  web:
    build: ./web
    volumes: 
      - app_volume:/opt/apache-tomcat-10.1.8/webapps
    ports: 
      - 8080:8080
    depends_on: 
      - builder

volumes: 
  app_volume: