version: '3'

services:

  builder:
    build: ./builder
    volumes: 
      - app_volume:/opt/build

  web:
    build: ./web
    volumes: 
      - app_volume:/tmp
    ports: 
      - 8080:8080
    depends_on: 
      - builder

volumes: 
  app_volume: